sudo: required
language: julia
dist: xenial
python:
  - "3.7"
git:
  depth: 3
  quiet: true
julia:
  - 1.2
os:
  - linux
before_install:
  - julia -e 'using Pkg; Pkg.add("ADCME"); Pkg.add("Conda"); Pkg.add("PyCall")'
notifications:
  email: false
coveralls: false
jobs:
  include:
    - stage: "Documentation"
      julia: 1.2
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg;Pkg.add("Documenter"); Pkg.develop(PackageSpec(path=pwd())); Pkg.build("NNFEM");
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
cache:
  directories:
  - /home/travis/.julia/conda/3/