sudo: required
language: julia
dist: xenial
python:
  - "3.7"
git:
  depth: 3
  quiet: true
julia:
  - 1.3
os:
  - linux
notifications:
  email: false
coveralls: false
before_install:
  - sudo apt-get update
  - sudo apt-get install python3-pip
  - sudo apt-get install python3-setuptools
  - /usr/bin/python3 -m pip install --upgrade pip
  - /usr/bin/python3 -m pip install --user matplotlib
  - /usr/bin/python3 -m pip install --user numpy
  - /usr/bin/python3 -m pip install --user scipy
  - julia -e 'using Pkg; Pkg.add("Conda"); ENV["PYTHON"]="/home/travis/.julia/conda/3/bin/python"; Pkg.add("PyCall")'
jobs:
  include:
    - stage: "Documentation"
      julia: 1.2
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.add("Conda"); ENV["PYTHON"]="/home/travis/.julia/conda/3/bin/python"; Pkg.add("PyCall")'
        - julia --project=docs/ -e 'using Pkg;Pkg.add("Documenter"); Pkg.develop(PackageSpec(path=pwd())); Pkg.build("NNFEM");
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
cache:
  directories:
  - /home/travis/.julia/conda/3/